Psalm integration
laminas/laminas-config-aggregator-parameters pull request #10
Opened 2021-04-05 00:51 UTC by nathane

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Resolves #7

2021-04-07 11:00 UTC, boesing requested changes

2021-04-07 11:00 UTC, boesing commented on .github/workflows/psalm.yml
> +name: "Static Analysis by Psalm"
I'd suggest removing this workflow in favor of the laminas continous integration workflow:
https://gist.github.com/weierophinney/9decd19f76b7d9745c6559074053fa65

2021-04-07 11:00 UTC, boesing commented on src/LazyParameterPostProcessor.php
> +     * @psalm-param callable():array<array-key, mixed> $parameterProvider
This is less accurate than `array<string,mixed>`.
Please revert this change as parameters **MUST** have string keys.

2021-04-07 11:00 UTC, boesing commented on src/LazyParameterPostProcessor.php
> +     * @param array<array-key, mixed> $config
Please revert this change as parameters MUST have string keys.

2021-04-07 11:00 UTC, boesing commented on src/LazyParameterPostProcessor.php
> +     * @return array<array-key, mixed>
Please revert this change as the configuration returned by this configuration **MUST** have string keys.

2021-04-07 11:00 UTC, boesing commented on src/ParameterNotFoundException.php
> -    public function getKey() : string
By removing the `getKey` method, you are introducing BC break. Please revert this removal in order to preserve this method.

2021-04-07 11:00 UTC, boesing commented on src/ParameterPostProcessor.php
> +     * @return (array|mixed)[]
Applying suggested changes from psalm is not helpful.
Please remove this change as it adds 0 value.

2021-04-07 11:00 UTC, boesing commented on src/ParameterPostProcessor.php
> +     * @psalm-return array{parameters: array}
This is not correct. The return value of this method returns more than just the parameters.
Please use the suggested annotation instead.
```suggestion
     * @psalm-return array<string,mixed>
```

2021-04-07 11:00 UTC, boesing commented on src/ParameterPostProcessor.php
> +            array_walk_recursive($config, function (string &$value) use ($parameters) {
Please do not cast any value in the config to a string.
Parameters can be `float`, `boolean`, `integer`, `array`, `null` (so just *any* type).
Casting to `string` breaks almost any implementation.

2021-04-07 11:00 UTC, boesing commented on src/ParameterPostProcessor.php
> +        /** @var string|array $value */
The value is mixed here and that is absolutely okay as parameter values can have almost any type.
If psalm complains about it, feel free to suppress the error by using `@psalm-suppress`

2021-04-07 11:00 UTC, boesing commented on src/ParameterPostProcessor.php
> +
Please try to avoid unrelated changes

2021-04-07 11:00 UTC, boesing commented on test/ParameterPostProcessorTest.php
> +     * @return (string|string[])[][][]
You should avoid applying psalm suggestions as these do not provide any helpful value for consumers/maintainers.
The structure of the returned array is 

```
@psalm-return array<string,array{0:array<string,mixed>,1:array{config:array{param:string,used_parameter:string}},2:array{param:mixed,used_parameter:string}}>
```

As you can see, this is ma little bit less detailed **but** if we have to add new unit tests here, we do not have to refactor the whole return type. So if we have an integer parameter we want to test, the return annotation is still valid!

2021-04-07 11:00 UTC, boesing commented on test/ParameterPostProcessorTest.php
> +     * @return void
There is no need to annotate this twice. native return type is absolutely okay as you've done in all the other tests in the same file.

2021-04-07 17:16 UTC, nathane commented on src/ParameterPostProcessor.php
> +            array_walk_recursive($config, function (string &$value) use ($parameters) {
Shouldn't the tests have failed to indicate this?

2021-04-07 17:46 UTC, boesing commented on src/ParameterPostProcessor.php
> +            array_walk_recursive($config, function (string &$value) use ($parameters) {
yes, but obviously these kind of tests are missing. 
Gonna create an issue for that.

2021-04-07 17:49 UTC, boesing commented on src/ParameterPostProcessor.php
> +            array_walk_recursive($config, function (string &$value) use ($parameters) {
Created #11, thanks for pointing this out.

2021-04-17 21:57 UTC, nathane commented
@boesing ping for final review.

2021-04-17 22:01 UTC, nathane commented on test/ParameterPostProcessorTest.php
> +     * @psalm-return array{root-scoped-parameter: array{0: array{foo: string}, 1: array{config: array{param: string, used_parameter: string}}, 2: array{config: array{param: string, used_parameter: st
CS failure due to `@psalm-return` DocBlock.

2021-04-25 16:32 UTC, boesing commented
@ghostwriter Please focus on the PR title. 
I've written a quite long comment in the `laminas-cache-storage-adapter-test` package and now closing this.
Having PRs like these are hard to review. Feel free to seperate your PRs into severel PRs.

1. Psalm integration (please do not remove already typed return values in any way and try to avoid psalms "alter" logic as it adds too much noise)
2. Codestandard 2.0 integration
3. Composer normalization

2021-04-25 16:32 UTC, closed without merging

2021-04-25 18:27 UTC, ghostwriter commented
@boesing Too lazy to click on 18 individual commits, that elegantly encapsulate each action taken? 

Even on a mobile device, GitHub displays all changes that occurred in a single commit separately.

Saying my commits are “impossible to review” is deliberate gross exaggeration.

Assuming you all (laminas org) followed the same guidelines, I was just trying to add as much value to the PR, to help expedite things by consolidating multiple “Features” into a single PR, following @weierophinney’s footsteps (who did the exact same thing I did in this PR, to not one but two separate PRs that I submitted so far.

That said, 
- **I’ll correct this going forward.**
- I’ll `git cherry-pick` the commits of this PR and make multiple PRs during my next available “free” time.

Have a great weekend!

P.S. Regarding Psalm I only changed what was originally there because it was complaining about it being incorrect. Now it’s not.

P.P.S Regarding the other PR you mentioned: Why did you merge a PR that you expertly said was “impossible to review”, leading the reader to believe that you did not review it? What if it had malicious code?